name: uplights

namespace: uplights
env:
  APP_VERSION: cd1c7ef77ac99857172a7fee5f3ac3d903c66f37

deployment:
  # - name: uplights-broker
  #   image: eclipse-mosquitto:1.6
  #   ports:
  #   - port: 1883
  #   - port: 9001

  - name: uplights-controller
    image: invisibug/uplights-controller
    ports:
    - port: 27017
    env:
    - name: MONGO
      value: mongodb://kavanest-mongo

    - name: MQTT
      value: mqtt:mqtt.kavanet.io

# service:
#   clusterIP:
#     - name: uplights
#       selector: uplights
#       ports:
#         - port: 3100

# ingress:
#   - name: uplights.kavanet.io
#     selector: uplights-broker
#     path: /
#     port: 1883
#     host: uplights.kavanet.io
